github.com:
    users:
        miroqu369:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: miroqu369
